title: Mozilla Growth & Usage Dashboard
github_url: https://github.com/mozilla/gud
# description of the web site
# It will appear in your document head meta (for Google search results)
description: The Mozilla Growth & Usage Dashboard (GUD) is a tool to visualize growth metrics in a standard way across Mozilla’s products.
url: "https://mozilla.github.io" # the base hostname & protocol for your site


theme: minima
markdown: kramdown
